# mm_client runtime settings
# Paths can be absolute or relative to this file.

main:
  # メインループ周期 (秒)
  loop_period: 0.1
  # ユーザ発話待ちタイムアウト (秒)  T.Oで "user_silence"通知
  max_user_wait_time: 10.0
  # 音声ログ保存の有無
  audio_logging: false

stt:
  # Google Speech-to-Text and Text-to-Speech サービスアカウントキー(json)
  key_file: 

dialbb:
  # DialBB application config used by DialogueProcessor
  config_file: 
