# configuration file for a chatgpt-based Japanese application

blocks:
  - name: mp1
    block_class: dialbb.builtin_blocks.chatgpt_mp.chatgpt_mp.ChatGPT
    language: ja
    input:
      user_id: user_id
      user_utterance: user_utterance
      aux_data: aux_data
    output:
      system_utterance: system_utterance
      aux_data: aux_data
      final: final
    participant_id: "田中"
    system_personality: "あなたは田中です。あなたは寿司が好きで、せっかちで、良くしゃべります"
    postfix: "あなたは次に話しますか？話すとすると何を話しますか？話さない場合は「黙る」と答えてください。"
    gpt_model: gpt-3.5-turbo
    

