# 状態遷移ネットワークベースの日本語サンプルアプリのコンフィギュレーションファイル

language: ja   # 言語を指定

blocks:  # ブロックのリスト
  - name: canonicalizer  # ブロック名
    # ブロックのクラス
    block_class: preprocess.utterance_canonicalizer.UtteranceCanonicalizer 
    input: # ブロックへの入力
      input_text: user_utterance
    output: # ブロックからの出力
      output_text: canonicalized_user_utterance
  - name: understander
    block_class: understanding_with_snips.snips_understander.Understander
    input:
      input_text: canonicalized_user_utterance
    output: 
      nlu_result: nlu_result
    knowledge_google_sheet:
      sheet_id: <google sheetのID>
          # https://docs.google.com/spreadsheets/d/.../edit#gid=0 の ...の部分
      key_file: <google sheets APIのキーファイル>
  - name: manager
    block_class: stn_management.stn_manager.Manager
    knowledge_google_sheet:
      sheet_id: <google sheetのID>
      key_file: <google sheets APIのキーファイル>
    function_definitions: scenario_functions  # 知識記述の中で用いる関数の定義ファイル
    input:
      sentence: canonicalized_user_utterance
      nlu_result: nlu_result
      user_id: user_id
    output:
      output_text: system_utterance
      final: final
    
