# configuration file for a state transition network-based English sample app

language: en

blocks:
  - name: canonicalizer  # canonicalizer block
    block_class: preprocess.utterance_canonicalizer.UtteranceCanonicalizer
    input:
      input_text: user_utterance
    output:
      output_text: canonicalized_user_utterance
  - name: understander # snips based understander block
    block_class: understanding_with_snips.snips_understander.Understander
    input:
      input_text: canonicalized_user_utterance
    output: 
      nlu_result: nlu_result
    knowledge_file: sample-knowledge-en.xlsx  # scenario excel
  - name: manager  # state transition network-based dialogue manager block
    block_class: stn_management.stn_manager.Manager
    knowledge_file: sample-knowledge-en.xlsx  # scenario excel
    function_definitions: scenario_functions # developer defined functions used in the scenario
    input:
      sentence: canonicalized_user_utterance
      nlu_result: nlu_result
      session_id: session_id
      user_id: user_id
    output:
      output_text: system_utterance
      aux_data: aux_data
      final: final
    

