# configuration file for a state transition network-based English sample app

language: en

blocks:
  - name: canonicalizer  # canonicalizer block
    block_class: dialbb.builtin_blocks.preprocess.simple_canonicalizer.SimpleCanonicalizer
    input:
      input_text: user_utterance
    output:
      output_text: canonicalized_user_utterance
  - name: tokenizer  # tokenize block
    block_class: dialbb.builtin_blocks.tokenization.whitespace_tokenizer.WhitespaceTokenizer
    input:
      input_text: canonicalized_user_utterance
    output: 
      tokens: tokens
  - name: understander # snips based understander block
    block_class: dialbb.builtin_blocks.understanding_with_snips.snips_understander.Understander
    canonicalizer:
      class: dialbb.builtin_blocks.preprocess.simple_canonicalizer.SimpleCanonicalizer
    tokenizer:
      class: dialbb.builtin_blocks.tokenization.whitespace_tokenizer.WhitespaceTokenizer
    input:
      tokens: tokens
    output: 
      nlu_result: nlu_result
    knowledge_file: sample-knowledge-en.xlsx  # scenario excel
    num_candidates: 1
  - name: manager  # state transition network-based dialogue manager block
    block_class: dialbb.builtin_blocks.stn_management.stn_manager.Manager
    knowledge_file: sample-knowledge-en.xlsx  # scenario excel
    function_definitions: scenario_functions # developer defined functions used in the scenario
    input:
      sentence: canonicalized_user_utterance
      nlu_result: nlu_result
      user_id: user_id
    output:
      output_text: system_utterance
      final: final
    
    

