language: en   # specify language

blocks:  # list of blocks
  - name: manager
    block_class: dialbb.builtin_blocks.stn_management.stn_manager.Manager
    knowledge_file: scenario.xlsx # scenario file
    function_definitions: scenario_functions
    input:
      sentence: user_utterance
      nlu_result: nlu_result
      user_id: user_id
      aux_data: aux_data
    output:
      output_text: system_utterance
      final: final
      aux_data: aux_data
    repeat_when_no_available_transitions: yes
    llm:
      model: gpt-4o-mini  # gpt-4o
      temperature: 0.7
      situation:
        - You are a dialogue system and chatting with the user.
        - You met the user for the first time.
        - You and the user are similar in age.
        - You and the user talk in a friendly manner.
      persona:
        - Your name is Matt
        - 21 years old
        - Male
        - You like sandwiches
        - You don't drink alcohol
        - A colledge student
        - Single
        - You talk very friendly
        - Diplomatic and cheerful
      cautions:
        - Do not generate long sentences
        - Do not put period at the end of sentences

