# Configuration for the English experimental application

language: en  # specify language

system_name: "sandwich bot"

blocks:  # list of blocks
  - name: canonicalizer  # block name
    # block class
    block_class: dialbb.builtin_blocks.preprocess.simple_canonicalizer.SimpleCanonicalizer
    input: # input to the block
      input_text: user_utterance
    output: # output from the block
      output_text: canonicalized_user_utterance
  - name: understander
    block_class: dialbb.builtin_blocks.understanding_with_chatgpt.chatgpt_understander.Understander
    input:
      input_text: canonicalized_user_utterance
    output: 
      nlu_result: nlu_result
    knowledge_file: lab_app_en_knowledge.xlsx  # nlu knowledge description
    canonicalizer:
      class: dialbb.builtin_blocks.preprocess.simple_canonicalizer.SimpleCanonicalizer
    flags_to_use:
      - 'Y'
      - 'T'
    sudachi_normalization: yes
    num_candidates: 3
  - name: ner
    block_class: dialbb.builtin_blocks.ner_with_spacy.ne_recognizer.SpaCyNER
    input:
      input_text: user_utterance
      aux_data: aux_data
    output:
      aux_data: aux_data
    model: en_core_web_trf
    patterns:
      - label: Date
        pattern: yesterday
  - name: manager
    block_class: dialbb.builtin_blocks.stn_management.stn_manager.Manager
    knowledge_file: lab_app_en_knowledge.xlsx # knowledge description file
    function_definitions: scenario_functions  # definition of functions used in the scenario
    scenario_graph: yes
    input:
      sentence: canonicalized_user_utterance
      nlu_result: nlu_result
      user_id: user_id
      aux_data: aux_data
    output:
      output_text: system_utterance
      final: final
      aux_data: aux_data      
    repeat_when_no_available_transitions: yes
    input_confidence_threshold: 0.5
    confirmation_request:
      function_to_generate_utterance: generate_confirmation_request
      acknowledgement_utterance_type: "yes"
      denial_utterance_type: "no"
    #utterance_to_ask_repetition: "could you say that again?"
    ignore_out_of_context_barge_in: yes
    reaction_to_silence:
      action: repeat
      #destination: state1
    flags_to_use:
      - 'Y'
      - 'T'
    
    
